### ISSUE TITLE
create_index_if_missing doesn't exist

### ISSUE THREAD

**Issue by sixninetynine** [aparo/pyes#489]
>>> from pyes import ES
    >>> es = ES('127.0.0.1:9200')
    >>> es.create_index_if_missing(index)
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
    AttributeError: 'ES' object has no attribute 'create_index_if_missing'

**Comment by mavarick** [comment]
use: 
    es.indices.create_index_if_missing

**Comment by sixninetynine** [comment]
thanks, I ended up rolling back to a previous version!

**Comment by mavarick** [comment]
yeah, most pyes docs, including official one are not for new version, it makes confusion!
